### ISSUE TITLE
tiqr crashes when it has no permission to use the camera.

### ISSUE THREAD

**Issue by joostd** [SURFnet/tiqr-client-ios#12]
tiqr crashes when it has no permission to use the camera.

To reproduce: start tiqr when no permission to use the camera is given, press 'Scan'.
(tiqr is not asking for permission to use the camera)

Reported by @thijskh, using tiqr 2.4.1 on iOS 9.2

**Comment by ijansch** [comment]
Issue can be closed, the above pull request #13 fixes it.

**Comment by thijskh** [comment]
This still happens for me after updating to tiqr 2.5. Was this included in the release?
Let me know if I can provide any help.

**Comment by eefjevanderharst** [comment]
Problem still exists in Build #36 . App crashes after I press 'scannen'.  It is no longer possible to manage 'camera permissions' via 'instellingen', so this is a catch-22?
![img_1852](https://cloud.githubusercontent.com/assets/8789958/19720014/9e683b5a-9b6c-11e6-9eb6-77cba0c19a78.png)

Tested with iOS 10.1, ipHone 5.

**Comment by eefjevanderharst** [comment]
Any update on this? App still crashes when camera permissions are missing. Tested with build #36, iOS 10.1.1 on iPhone 5s.

**Comment by joostd** [comment]
tested fix in build #42
