### ISSUE TITLE
iOS: pincode te vaak verkeerd ingevuld dan heb je geen ‘back button’

### ISSUE THREAD

**Issue by Appmakelaar** [SURFnet/tiqr-client-ios#21]
@joostd wat is het gewenste gedrag van de 'back button'? Bij 'account blocked' als je hier de 'back button' toevoegt naar welk scherm ga je dan? Teruggaan naar de scanner is niet mogelijk omdat je account geblokkeerd is. Met het icon (rechtsboven) kan je je account verwijderen.

zie graag uit naar je input

**Comment by joostd** [comment]
Good question. The only way to return to the scanner is now to delete all accounts, but as those accounts are permanently blocked anyway, I guess that's fine for now.
