### ISSUE TITLE
Entering wrong pin leads to unknown_error

### ISSUE THREAD

**Issue by eefjevanderharst** [SURFnet/tiqr-client-ios#26]
When I enter a wrong pin in the tiqr authentication flow I receive the following error message:
unknown_error
Onbekende fout

Why this error? App should detect that I have entered the wrong pin. Translation missing? 

![tiqr bug pin](https://cloud.githubusercontent.com/assets/8789958/21849206/e8c042ae-d804-11e6-9207-472dbbda8bf1.png)

Tested with build #43,  iPhone 4, iOS 9.3.5 language settings NL.

**Comment by 7hommay** [comment]
@eefjevanderharst I can't seem to reproduce this using https://demo.tiqr.org/v1/. Was this a fresh install of the app?

**Comment by eefjevanderharst** [comment]
@ 7hommay yes this was a fresh install. Cannot reproduce it either on  https://demo.tiqr.org/v1/.

@joostd problem occured when I tried to authenticate with wrong tiqr PIN in the RA portal: https://ra.test.surfconext.nl/. Maybe this error is only related to communication between tiqr IDP and RA-portal (test)? And therefor not relevant for this release?

**Comment by joostd** [comment]
not a client issue
